import type { Track, Vec2 } from './engine/keyframes';

/**
 * Types for FlashMotion Studio - Adobe Flash & Remotion Hybrid Studio
 */

/** Stage tools (left toolbar). */
export type StageTool = 'pointer' | 'transform' | 'pen' | 'line' | 'arrow' | 'rect' | 'circle' | 'eraser' | 'path';

export interface CanvasDimensions {
  width: number;
  height: number;
  preset: 'youtube-1080p' | 'youtube-720p' | 'youtube-shorts' | 'square' | 'portrait' | 'ultrawide' | 'custom';
}

/** Output size presets. Labels are translated as `canvas.preset.<id>`. */
export const CANVAS_PRESETS: {
  id: CanvasDimensions['preset'];
  width: number;
  height: number;
  ratio: string;
}[] = [
  { id: 'youtube-1080p', width: 1920, height: 1080, ratio: '16:9' },
  { id: 'youtube-720p', width: 1280, height: 720, ratio: '16:9' },
  { id: 'youtube-shorts', width: 1080, height: 1920, ratio: '9:16' },
  { id: 'square', width: 1080, height: 1080, ratio: '1:1' },
  { id: 'portrait', width: 1080, height: 1350, ratio: '4:5' },
  { id: 'ultrawide', width: 2560, height: 1080, ratio: '21:9' },
];

export interface Point {
  x: number;
  y: number;
}

export interface Joint {
  id: string;
  name?: string;
  x: number;
  y: number;
  parent?: string;
  radius?: number;
  color?: string;
  isControlPoint?: boolean;
}

export interface Bone {
  id: string;
  from: string; // joint id
  to: string;   // joint id
  thickness?: number;
  color?: string;
}

export interface StickFigure {
  id: string;
  name: string;
  color: string;
  thickness: number;
  scale: number;
  x: number;
  y: number;
  joints: Record<string, Joint>;
  bones: Bone[];
  groupId?: string;
  /** Generated by a pose tween (in-between), not posed by hand. Shown as a dot on the timeline. */
  tweened?: boolean;
}

export interface DrawingStroke {
  id: string;
  tool: 'pen' | 'line' | 'rect' | 'circle' | 'arrow';
  points: Point[];
  color: string;
  thickness: number;
  fill?: string;
  groupId?: string;
}

export interface CanvasGroup {
  id: string;
  name: string;
  x: number;
  y: number;
  scale: number;
  rotation: number;
  strokeIds: string[];
  stickFigureId?: string;
}

export interface ChartDataPoint {
  label: string;
  value: number;
  color: string;
}

export type ChartType = 'bar' | 'donut' | 'line' | 'stat';

/**
 * A chart card. Its transform (position = card center, scale, rotation, opacity) is animated like any
 * actor; `animationType`/`easing`/`animDurationFrames` drive the intro of the content (bars growing…).
 */
export interface ChartOverlay extends Animated {
  id: string;
  title: string;
  type: ChartType;
  width: number;
  height: number;
  data: ChartDataPoint[];
  statMetric?: {
    value: string;
    suffix: string;
    label: string;
  };
  animationType: 'grow' | 'fade' | 'bounce' | 'slideUp' | 'elastic';
  visible: boolean;
  /** Easing and length of the content intro (not of the movement, which uses keyframes). */
  easing?: IntroEasing;
  animDurationFrames?: number;
}

export type IntroEasing = 'easeOut' | 'easeInOut' | 'linear' | 'bounce';

export type TextEffect =
  | 'typewriter'
  | 'bouncePop'
  | 'slideLeft'
  | 'glowPulse'
  | 'fadeRise'
  | 'numberRoll'
  /** No intro of its own: the text only moves with its keyframes. */
  | 'none';

/**
 * A title or number counter. Its transform is animated like any actor; the anchor (position) is the
 * start of the text baseline. `effect` is the intro of the text itself (typewriter, counter…).
 */
export interface TextOverlay extends Animated {
  id: string;
  text: string;
  subtitle?: string;
  fontSize: number;
  color: string;
  bgColor?: string;
  effect: TextEffect;
  badge?: string;
  visible: boolean;
  // Number counter capabilities
  isNumberCounter?: boolean;
  counterStart?: number;
  counterEnd?: number;
  counterPrefix?: string;
  counterSuffix?: string;
  counterDecimals?: number;
  /** Easing and length of the intro effect / counter. */
  easing?: IntroEasing;
  animDurationFrames?: number;
}

export interface ImageOverlay {
  id: string;
  url: string;
  x: number; // canvas pixels 0..1280
  y: number; // canvas pixels 0..720
  width: number;
  height: number;
  startFrame: number;
  durationFrames: number;
  animationType: 'pop' | 'fade' | 'float';
}

/** Animatable transform of an actor. Rotation in degrees, opacity 0..1, scale 1 = base size. */
export interface ActorTransform {
  x: number;
  y: number;
  scale: number;
  rotation: number;
  opacity: number;
}

export interface MotionTracks {
  position?: Track<Vec2>;
  scale?: Track<number>;
  rotation?: Track<number>;
  opacity?: Track<number>;
}

/**
 * Anything on the stage that moves the After Effects way: a time span plus a transform whose
 * properties are static (`base`, stopwatch off) or keyframed (`tracks`, stopwatch on), optionally
 * travelling a drawn path. Actors, charts and texts all share it (logic in `engine/actor.ts`).
 */
export interface Animated {
  startFrame: number;
  durationFrames: number;
  base: ActorTransform;
  tracks: MotionTracks;
  /** Curved path through position keys (AE Auto Bezier) instead of straight lines. */
  smoothPath: boolean;
  /** Rotate to follow the direction of travel (Flash "Orient to path"). */
  orientToPath: boolean;
  /**
   * Follow a motion path (Flash "motion guide"): while set, the position comes from the path and
   * `progress` (0 = first point, 1 = last point) is keyframed like any other property.
   */
  follow?: ActorFollow;
}

/**
 * Actor ("símbolo" in Flash, "layer" in After Effects): an imported image animated by keyframe tracks.
 * A property without keys uses its `base` value (AE stopwatch off); once it has keys, edits at the
 * current frame create/update keys (stopwatch on).
 */
export interface ActorOverlay extends Animated {
  id: string;
  name: string;
  kind: 'image';
  /** Image as data URL so projects can be saved to a single file. */
  src: string;
  /** Size at scale 1, in canvas pixels. The anchor point is the image center. */
  width: number;
  height: number;
  /** Mirror horizontally (e.g. a plane image drawn facing the other way). */
  flipX: boolean;
  /** Draws the path already travelled behind the actor (e.g. a dashed flight line). */
  trail?: { enabled: boolean; color: string; width: number; dashed: boolean };
}

export interface ActorFollow {
  pathId: string;
  progress: Track<number>;
  /** Rotate to the path direction. */
  orient: boolean;
}

export type PathStrokeStyle = 'solid' | 'dashed' | 'dotted';

/**
 * A drawn motion path ("rota"/"guia"): a line through points that actors can follow. It can be visible
 * (dotted route) or just a guide, and can reveal itself as its followers travel it.
 */
export interface MotionPath {
  id: string;
  name: string;
  points: Vec2[];
  /** Curve through the points (centripetal Catmull-Rom) instead of straight segments. */
  smooth: boolean;
  closed: boolean;
  style: {
    visible: boolean;
    color: string;
    width: number;
    stroke: PathStrokeStyle;
    /** 'full': always drawn; 'follow': only the part already travelled by an actor following it. */
    reveal: 'full' | 'follow';
  };
  startFrame: number;
  durationFrames: number;
}

/**
 * A sound on the timeline (narration, music, effect): used as timing reference while animating and
 * mixed into the export. The file is embedded so the project stays a single file.
 */
export interface AudioClip {
  id: string;
  name: string;
  /** Audio file as a data URL. */
  src: string;
  /** Length of the whole source, in seconds. */
  sourceDuration: number;
  /** Timeline frame where the clip starts playing. */
  startFrame: number;
  /** Seconds skipped at the beginning of the source (trim). */
  offset: number;
  /** Seconds played from `offset` on (trim at the end). */
  duration: number;
  /** Gain, 0..2 (1 = original level). */
  volume: number;
  muted: boolean;
}

export interface FrameData {
  frameNumber: number;
  stickFigures: StickFigure[];
  drawings: DrawingStroke[];
  groups?: CanvasGroup[];
}

export type LayerType = 'drawing' | 'chart' | 'text' | 'group' | 'video' | 'image' | 'actor' | 'path';

export interface StudioLayer {
  id: string;
  name: string;
  type: LayerType;
  visible: boolean;
  locked: boolean;
  color: string;
  opacity?: number;
  targetId?: string; // links to specific chart, text, stick, or group
}

export interface VideoBackground {
  type: 'preset' | 'upload' | 'color';
  url?: string;
  color?: string;
  opacity: number;
  playbackRate: number;
}

export type SelectedObjectType =
  | 'stick'
  | 'chart'
  | 'text'
  | 'image'
  | 'drawing'
  | 'group'
  | 'actor'
  | 'path'
  | null;

export interface SelectedObjectRef {
  type: SelectedObjectType;
  id: string;
}

export interface HistorySnapshot {
  description: string;
  layers: StudioLayer[];
  frames: Record<number, FrameData>;
  charts: ChartOverlay[];
  texts: TextOverlay[];
  images: ImageOverlay[];
  actors: ActorOverlay[];
  paths: MotionPath[];
  audio?: AudioClip[];
  groups?: CanvasGroup[];
  videoBg?: VideoBackground;
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: number;
  actionPayload?: {
    type: 'chart' | 'text' | 'pose' | 'script';
    data: any;
  };
}

export type ChatRole = 'general' | 'choreographer' | 'educator' | 'generator';
